ecommerceproject/cart/urls.py
from django.urls import path
from . import views
app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/',views.add_cart,name="add_cart"),
    path('',views.cart_detail,name="cart_detail"),
    path('remove/<int:product_id>/',views.cart_remove,name="cart_remove"),
    path('full_remove/<int:product_id>/',views.full_remove,name="full_remove")

]

ecommerceproject/ecommerceproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from mycart import views
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('',views.home,name='home')
    path('mycart/',include("mycart.urls")),
    path('search/',include("search_app.urls")),
    path('cart/',include("cart.urls")),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/mycart/urls.py
from django.urls import path, include
from . import views
app_name='mycart'


urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.ProdCatDetail,name='ProdCatDetail'),
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),

]

ecommerceproject/search_app/urls.py
from django.urls import path
from . import views

app_name="search_app"

urlpatterns=[

    path('',views.SearchResult,name="SearchResult"),
]

ecommerceproject/cart/models.py
from django.db import models
from mycart.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)
    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'

    def sub_total(self):
        return self.product.price*self.quantity
    def __str__(self):
        return self.product

ecommerceproject/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from mycart.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:

            cart_item.quantity += 1
        cart_item.save();
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()
    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, "cart.html", {'cart_items': cart_items, 'total': total, 'counter': counter})

def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity>1:
        cart_item.quantity-=1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Antonio:wght@200&family=Roboto:wght@300&display=swap" rel="stylesheet">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>
<div>
<!--    {% include 'header.html' %}-->
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}

</div>
<div>
    {% include 'footer.html' %}
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="{% static 'popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    
</div>

</body>
</html>

ecommerceproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    welcome to the ecart store
{% endblock %}

{% block title %}
    ekark - buy your favourite !!!
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart is empty

        </h1>
        <br>
        <p class="text-center">
            Please click<a href="{% url 'mycart:allProdCat' %}">Here</a>
        </p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
        Your Shopping Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">Your Items</th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url"><img src={{cart_item.product.image.url}} class="float-left rounded custom_image"></a>
                </td>
                <td class="text-left">

                    {{cart_item.product.name}}
                    <br>
                    batch no. {{cart_item.product.id}}
                    <br>
                    Unit Price : {{cart_item.product.price}}
                    QTY: {{cart_item.quantity}} *  $ {{cart_item.product.price}}
                </td>
                <td>$ {{cart_item.sub_total}}</td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fas fa-plus custom_icon"></i></a>&nbsp;
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-minus custom_icon"></i> </a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i> </a>
                </td>
                {% else %}
                <td>
                    &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fas fa-minus custom_icon"></i> </a>&nbsp;
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fas fa-trash-alt custom_icon"></i> </a>

                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    please review your shopping cart items before proceeding with the order payment.
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    Your total amount is <strong>  ${{ total }} </strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'mycart:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">Continue Shopping</a>

</div>
    </div>
</div><br>
{% endif %}
{% endblock %}

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.desc |truncatewords:155 }}
    {% else %}
        welcome to our shop
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{category.name}}-ekart
    {% else %}
         ekart-the complete online shop
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'mycart:allProdCat' %}" >our product collections</a> | {{category.name}}</p>
            </div>
        </div>
    {% endif %}
<div class="mx-auto">
        {% if category %}
            <img class="my_image" src="{{category.image.url}}"alt="{{category.name}}">

</div><br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.desc}}</p>
</div>
        {% else %}
            <div>
              <center><img class="my_image my_image_padding" src="{% static 'img/ekart.png' %}" style="width:1350px;height:350px"alt=""></center>
            </div>
<br>
<div>
    <h1 class="text-center my_title">our product collections</h1>
    <p class="text-justify">Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book.</p>
        {% endif %}
<div class="container">
    <div class="row max-auto">
        {% for product in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}"style="width:250px;height:250px"alt="{{product.name}}">
                </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        <div class="text-center">
        {% for pg in products.paginator.page_range %}
        <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} activate {% endif %}">{{pg}}</a>
        {% endfor %}
            </div>
</div>
</div>
</div>
    {% endblock %}

ecommerceproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
<p class="text-center">&copy; Avodha Training. All Rights Reserved.</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<div class="my_header" xmlns="http://www.w3.org/1999/html">
<center>
        <img src="{% static 'img/ekart (1).png' %}"  style="width:100px;" alt='this is cart logo'>
</center>
</div>

ecommerceproject/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    You can login here....
{% endblock %}

{% block title %}
    ekark - login
{% endblock %}
{% block content %}

<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="css/custom.css" rel="stylesheet" type="text/css" media="all" />
<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
<center>
	<div class="main-w3layouts wrapper">
		<h1>Login Here...</h1>
		<div class="main-agileinfo">
			<div class="agileits-top">
     <form action="login" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="username"><br>
    <input type="password" name="password" placeholder="password"><br>
    <input type="submit" value="login">
    {% for message in messages %}
    <h4>{{message}}</h4>
    {% endfor %}
</form>
     </div>
        </div>
            </div>

</center>


{% endblock %}

ecommerceproject/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" xmlns="http://www.w3.org/1999/html">
<!--  <a class="navbar-brand" href="#">Navbar</a>-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <img src="{% static 'img/new.png' %}"  style="width:50px;" alt='this is cart logo'>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'mycart:allProdCat' %}">Home <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'mycart:allProdCat' %}">All Products</a>
            {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
            {% endfor %}
<!--          <div class="dropdown-divider"></div>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
        </div>
      </li>

      <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:SearchResult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search your favourites" aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>

<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#">Disabled</a>-->
<!--      </li>-->
    </ul>

      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart">{{item_count}}</i></a>
      </li>
      {% endif %}

      {% if user.is_authenticated %}
    <li class="nav-item active"><a class="nav-link" href=""><i class="fas fa-user"></i><strong>"Hai {{user.first_name}}</strong></i><span class="sr-only">(current)</span></a></li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'mycart:logout' %}"><strong>Logout </strong><span class="sr-only">(current)</span></a>
      </li>
      {% else %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'mycart:login' %}"><strong>Login</strong> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'mycart:register' %}"><strong>Register </strong><span class="sr-only">(current)</span></a>
      </li>
      {% endif %}


  </div>
</nav>
<!--<nav>-->
<!--   <dl>-->
<!--        <dt><a href="{% url 'mycart:allProdCat' %}">All Products</a></dt>-->
<!--        {% for cat in links %}-->
<!--        <dd><a href="{{cat.get_url}}">{{cat.name}}</a></dd>-->
<!--        {% endfor %}-->
<!--        <dt>your cart</dt>-->
<!--   </dl>-->
<!--</nav><br>-->

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        {{ product.desc |truncatewords:155 }}
{% endblock %}
{% block title %}
        {{product.name}}-ekart
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'mycart:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}"></a>{{product.name}} </p>

    </div>
    <div class="container">
        <br>
        <div class="row">
            <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
                <div style="min-width:18rem;">
                <img src="{{product.image.url}}"style="width:200px;height:200px" alt="{{product.name}}">
            </div>
        </div>
        <div class="col-12 col-sm-12 col-md-12 col-lg-6">
            <div>
                <h1 class="my_prod_title"><b>{{product.name}}</b></h1>
                <p>${{product.price}}</p>
                <p class="my_title">Product Description</p>
                <p class="text-justify my_prod_text">{{product.desc}}</p>
                {% if product.stock <= 0 %}
                    <p class="text-justify my_prod_text"><b> Out of stock </b></p>
                {% else %}
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

ecommerceproject/templates/registration.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
    You can register here....
{% endblock %}

{% block title %}
    ekark - Register here
{% endblock %}
{% block content %}
<!--<div>-->
<!--    <center><form action="register" method="post">-->
<!--    {% csrf_token %}-->
<!--    <input type="text" name="username" placeholder="username"><br>-->
<!--    <input type="text" name="firstname" placeholder="First name"><br>-->
<!--    <input type="text" name="lastname" placeholder="Last name"><br>-->
<!--    <input type="email" name="email" placeholder="email"><br>-->
<!--    <input type="password" name="password1" placeholder="password"><br>-->
<!--    <input type="password" name="password2" placeholder="re enter password"><br>-->
<!--    <input type="submit" value="register">-->
<!--    {% for message in messages %}-->
<!--    <h4>{{message}}</h4>-->
<!--    {% endfor %}-->
<!--</form>-->
<!--</center>-->
<!--</div>-->



<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="css/custom.css" rel="stylesheet" type="text/css" media="all" />
<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->

	<!-- main -->
<center>
	<div class="main-w3layouts wrapper">
		<h1>Register Here...</h1>
		<div class="main-agileinfo">
			<div class="agileits-top">
				<form action="register" method="post">
                    {% csrf_token %}
					<input class="text" type="text" name="username" placeholder="username" required=""><br>
                    <input class="text" type="text" name="firstname" placeholder="First name" required=""><br>
                    <input class="text" type="text" name="lastname" placeholder="Last name" required=""><br>
					<input class="text email" type="email" name="email" placeholder="Email" required=""><br>
					<input class="text" type="password" name="password1" placeholder="Password" required=""><br>
					<input class="text w3lpass" type="password" name="password2" placeholder="Confirm Password" required=""><br>
					<div class="wthree-text">
						<label class="anim">
							<input type="checkbox" class="checkbox" required="">
							<span>I Agree To The Terms & Conditions</span>
						</label>
						<div class="clear"> </div>
					</div>
					<input type="submit" value="SIGNUP">
                    {% for message in messages %}
                     <h4>{{message}}</h4>
                    {% endfor %}
				</form>
				<p>Already have an Account? <a href="{% url 'mycart:login' %}"> Login Now!</a></p>
			</div>
		</div>
		<!-- copyright -->
<!--		<div class="colorlibcopy-agile">-->
<!--			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>-->
<!--		</div>-->
<!--		 //copyright-->
		<ul class="colorlib-bubbles">

		</ul>
	</div>
</center>
{% endblock %}

ecommerceproject/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        {{ product.desc |truncatewords:155 }}
{% endblock %}
{% block title %}
        {{product.name}}-ekart
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for: {{query}}</p>
</div>
<div class="container">
    <div class="row max-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="width: 18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}"style="width:250px;height:250px"alt="{{product.name}}">
                </a>
                <div class="card-body">
                    <h4>{{product.name}}</h4>
                    <p>${{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found.</p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}